import "./scss/style.scss";
import "./components/swiper.js";
import "./components/scroll-to-top.js";
import "./components/animate.js";
import "./components/accordion.js";
import "./components/megamenu.js";
import "./components/lightbox.js";
import "./components/filter.js";
import "./components/loadmore.js";